version: "2"
services:
  app:
    build: .
    restart: always
    ports:
    - 5000:5000
    environment:
      HOST_MONGODB: mongo
    volumes:
      - ./uploads:/usr/src/app/uploads
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
